# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/main/java/com/rb/nonbiz/math/eigen/EigenProto.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='src/main/java/com/rb/nonbiz/math/eigen/EigenProto.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n7src/main/java/com/rb/nonbiz/math/eigen/EigenProto.proto\"\xd8\x05\n\x12\x45igenDecomposition\x12\x19\n\x11human_description\x18\x01 \x01(\t\x12%\n\x1d\x65igenvector_coverage_fraction\x18\x02 \x01(\x01\x12\x30\n(sum_of_all_eigenvalues_including_skipped\x18\x03 \x01(\x01\x12G\n\x16\x61ll_quality_of_returns\x18\x04 \x03(\x0b\x32\'.EigenDecomposition.QualityOfReturnsMsg\x12\x45\n\x1eretained_eigenpairs_descending\x18\x05 \x03(\x0b\x32\x1d.EigenDecomposition.Eigenpair\x12J\n\x1ainstrument_factor_loadings\x18\x06 \x03(\x0b\x32&.EigenDecomposition.InstrumentLoadings\x12+\n\x05stats\x18\x07 \x03(\x0b\x32\x1c.EigenDecomposition.StatsMsg\x1a=\n\tEigenpair\x12\x12\n\neigenvalue\x18\x01 \x01(\x01\x12\x1c\n\x14\x65igenvector_elements\x18\x02 \x03(\x01\x1aI\n\x12InstrumentLoadings\x12\x15\n\rinstrument_id\x18\x01 \x01(\x03\x12\x1c\n\x14\x65igenvector_loadings\x18\x02 \x03(\x01\x1aq\n\x13QualityOfReturnsMsg\x12\x15\n\rinstrument_id\x18\x01 \x01(\x03\x12\x12\n\nnum_actual\x18\x02 \x01(\x05\x12\x16\n\x0enum_gap_filled\x18\x03 \x01(\x05\x12\x17\n\x0fnum_back_filled\x18\x04 \x01(\x05\x1aH\n\x08StatsMsg\x12\x15\n\rinstrument_id\x18\x01 \x01(\x03\x12%\n\x1d\x61nnualized_standard_deviation\x18\x02 \x01(\x01\x42\x1a\n\x18\x63om.rb.nonbiz.math.eigenb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_EIGENDECOMPOSITION_EIGENPAIR = _descriptor.Descriptor(
  name='Eigenpair',
  full_name='EigenDecomposition.Eigenpair',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='eigenvalue', full_name='EigenDecomposition.Eigenpair.eigenvalue', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='eigenvector_elements', full_name='EigenDecomposition.Eigenpair.eigenvector_elements', index=1,
      number=2, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=463,
  serialized_end=524,
)

_EIGENDECOMPOSITION_INSTRUMENTLOADINGS = _descriptor.Descriptor(
  name='InstrumentLoadings',
  full_name='EigenDecomposition.InstrumentLoadings',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='instrument_id', full_name='EigenDecomposition.InstrumentLoadings.instrument_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='eigenvector_loadings', full_name='EigenDecomposition.InstrumentLoadings.eigenvector_loadings', index=1,
      number=2, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=526,
  serialized_end=599,
)

_EIGENDECOMPOSITION_QUALITYOFRETURNSMSG = _descriptor.Descriptor(
  name='QualityOfReturnsMsg',
  full_name='EigenDecomposition.QualityOfReturnsMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='instrument_id', full_name='EigenDecomposition.QualityOfReturnsMsg.instrument_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='num_actual', full_name='EigenDecomposition.QualityOfReturnsMsg.num_actual', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='num_gap_filled', full_name='EigenDecomposition.QualityOfReturnsMsg.num_gap_filled', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='num_back_filled', full_name='EigenDecomposition.QualityOfReturnsMsg.num_back_filled', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=601,
  serialized_end=714,
)

_EIGENDECOMPOSITION_STATSMSG = _descriptor.Descriptor(
  name='StatsMsg',
  full_name='EigenDecomposition.StatsMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='instrument_id', full_name='EigenDecomposition.StatsMsg.instrument_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='annualized_standard_deviation', full_name='EigenDecomposition.StatsMsg.annualized_standard_deviation', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=716,
  serialized_end=788,
)

_EIGENDECOMPOSITION = _descriptor.Descriptor(
  name='EigenDecomposition',
  full_name='EigenDecomposition',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='human_description', full_name='EigenDecomposition.human_description', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='eigenvector_coverage_fraction', full_name='EigenDecomposition.eigenvector_coverage_fraction', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sum_of_all_eigenvalues_including_skipped', full_name='EigenDecomposition.sum_of_all_eigenvalues_including_skipped', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='all_quality_of_returns', full_name='EigenDecomposition.all_quality_of_returns', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='retained_eigenpairs_descending', full_name='EigenDecomposition.retained_eigenpairs_descending', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='instrument_factor_loadings', full_name='EigenDecomposition.instrument_factor_loadings', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stats', full_name='EigenDecomposition.stats', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_EIGENDECOMPOSITION_EIGENPAIR, _EIGENDECOMPOSITION_INSTRUMENTLOADINGS, _EIGENDECOMPOSITION_QUALITYOFRETURNSMSG, _EIGENDECOMPOSITION_STATSMSG, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=788,
)

_EIGENDECOMPOSITION_EIGENPAIR.containing_type = _EIGENDECOMPOSITION
_EIGENDECOMPOSITION_INSTRUMENTLOADINGS.containing_type = _EIGENDECOMPOSITION
_EIGENDECOMPOSITION_QUALITYOFRETURNSMSG.containing_type = _EIGENDECOMPOSITION
_EIGENDECOMPOSITION_STATSMSG.containing_type = _EIGENDECOMPOSITION
_EIGENDECOMPOSITION.fields_by_name['all_quality_of_returns'].message_type = _EIGENDECOMPOSITION_QUALITYOFRETURNSMSG
_EIGENDECOMPOSITION.fields_by_name['retained_eigenpairs_descending'].message_type = _EIGENDECOMPOSITION_EIGENPAIR
_EIGENDECOMPOSITION.fields_by_name['instrument_factor_loadings'].message_type = _EIGENDECOMPOSITION_INSTRUMENTLOADINGS
_EIGENDECOMPOSITION.fields_by_name['stats'].message_type = _EIGENDECOMPOSITION_STATSMSG
DESCRIPTOR.message_types_by_name['EigenDecomposition'] = _EIGENDECOMPOSITION

EigenDecomposition = _reflection.GeneratedProtocolMessageType('EigenDecomposition', (_message.Message,), dict(

  Eigenpair = _reflection.GeneratedProtocolMessageType('Eigenpair', (_message.Message,), dict(
    DESCRIPTOR = _EIGENDECOMPOSITION_EIGENPAIR,
    __module__ = 'src.main.java.com.rb.nonbiz.math.eigen.EigenProto_pb2'
    # @@protoc_insertion_point(class_scope:EigenDecomposition.Eigenpair)
    ))
  ,

  InstrumentLoadings = _reflection.GeneratedProtocolMessageType('InstrumentLoadings', (_message.Message,), dict(
    DESCRIPTOR = _EIGENDECOMPOSITION_INSTRUMENTLOADINGS,
    __module__ = 'src.main.java.com.rb.nonbiz.math.eigen.EigenProto_pb2'
    # @@protoc_insertion_point(class_scope:EigenDecomposition.InstrumentLoadings)
    ))
  ,

  QualityOfReturnsMsg = _reflection.GeneratedProtocolMessageType('QualityOfReturnsMsg', (_message.Message,), dict(
    DESCRIPTOR = _EIGENDECOMPOSITION_QUALITYOFRETURNSMSG,
    __module__ = 'src.main.java.com.rb.nonbiz.math.eigen.EigenProto_pb2'
    # @@protoc_insertion_point(class_scope:EigenDecomposition.QualityOfReturnsMsg)
    ))
  ,

  StatsMsg = _reflection.GeneratedProtocolMessageType('StatsMsg', (_message.Message,), dict(
    DESCRIPTOR = _EIGENDECOMPOSITION_STATSMSG,
    __module__ = 'src.main.java.com.rb.nonbiz.math.eigen.EigenProto_pb2'
    # @@protoc_insertion_point(class_scope:EigenDecomposition.StatsMsg)
    ))
  ,
  DESCRIPTOR = _EIGENDECOMPOSITION,
  __module__ = 'src.main.java.com.rb.nonbiz.math.eigen.EigenProto_pb2'
  # @@protoc_insertion_point(class_scope:EigenDecomposition)
  ))
_sym_db.RegisterMessage(EigenDecomposition)
_sym_db.RegisterMessage(EigenDecomposition.Eigenpair)
_sym_db.RegisterMessage(EigenDecomposition.InstrumentLoadings)
_sym_db.RegisterMessage(EigenDecomposition.QualityOfReturnsMsg)
_sym_db.RegisterMessage(EigenDecomposition.StatsMsg)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\030com.rb.nonbiz.math.eigen'))
# @@protoc_insertion_point(module_scope)
