# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/main/java/com/rb/nonbiz/math/beta/BetaProto.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='src/main/java/com/rb/nonbiz/math/beta/BetaProto.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n5src/main/java/com/rb/nonbiz/math/beta/BetaProto.proto\"\xdf\x02\n\x14\x42\x65tasForSingleDayMsg\x12\x19\n\x11human_description\x18\x01 \x01(\t\x12(\n max_num_days_in_beta_calculation\x18\x02 \x01(\x05\x12\x33\n\nbetas_from\x18\x03 \x03(\x0b\x32\x1f.BetasForSingleDayMsg.BetasFrom\x1as\n\x07\x42\x65tasTo\x12\x18\n\x10to_instrument_id\x18\x01 \x01(\x03\x12\x0c\n\x04\x62\x65ta\x18\x02 \x01(\x01\x12+\n#actual_num_days_in_beta_calculation\x18\x03 \x01(\x05\x12\x13\n\x0b\x63orrelation\x18\x04 \x01(\x01\x1aX\n\tBetasFrom\x12\x1a\n\x12\x66rom_instrument_id\x18\x01 \x01(\x03\x12/\n\x08\x62\x65tas_to\x18\x02 \x03(\x0b\x32\x1d.BetasForSingleDayMsg.BetasToB\x19\n\x17\x63om.rb.nonbiz.math.betab\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_BETASFORSINGLEDAYMSG_BETASTO = _descriptor.Descriptor(
  name='BetasTo',
  full_name='BetasForSingleDayMsg.BetasTo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='to_instrument_id', full_name='BetasForSingleDayMsg.BetasTo.to_instrument_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='beta', full_name='BetasForSingleDayMsg.BetasTo.beta', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='actual_num_days_in_beta_calculation', full_name='BetasForSingleDayMsg.BetasTo.actual_num_days_in_beta_calculation', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='correlation', full_name='BetasForSingleDayMsg.BetasTo.correlation', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=204,
  serialized_end=319,
)

_BETASFORSINGLEDAYMSG_BETASFROM = _descriptor.Descriptor(
  name='BetasFrom',
  full_name='BetasForSingleDayMsg.BetasFrom',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='from_instrument_id', full_name='BetasForSingleDayMsg.BetasFrom.from_instrument_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='betas_to', full_name='BetasForSingleDayMsg.BetasFrom.betas_to', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=321,
  serialized_end=409,
)

_BETASFORSINGLEDAYMSG = _descriptor.Descriptor(
  name='BetasForSingleDayMsg',
  full_name='BetasForSingleDayMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='human_description', full_name='BetasForSingleDayMsg.human_description', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max_num_days_in_beta_calculation', full_name='BetasForSingleDayMsg.max_num_days_in_beta_calculation', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='betas_from', full_name='BetasForSingleDayMsg.betas_from', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_BETASFORSINGLEDAYMSG_BETASTO, _BETASFORSINGLEDAYMSG_BETASFROM, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=409,
)

_BETASFORSINGLEDAYMSG_BETASTO.containing_type = _BETASFORSINGLEDAYMSG
_BETASFORSINGLEDAYMSG_BETASFROM.fields_by_name['betas_to'].message_type = _BETASFORSINGLEDAYMSG_BETASTO
_BETASFORSINGLEDAYMSG_BETASFROM.containing_type = _BETASFORSINGLEDAYMSG
_BETASFORSINGLEDAYMSG.fields_by_name['betas_from'].message_type = _BETASFORSINGLEDAYMSG_BETASFROM
DESCRIPTOR.message_types_by_name['BetasForSingleDayMsg'] = _BETASFORSINGLEDAYMSG

BetasForSingleDayMsg = _reflection.GeneratedProtocolMessageType('BetasForSingleDayMsg', (_message.Message,), dict(

  BetasTo = _reflection.GeneratedProtocolMessageType('BetasTo', (_message.Message,), dict(
    DESCRIPTOR = _BETASFORSINGLEDAYMSG_BETASTO,
    __module__ = 'src.main.java.com.rb.nonbiz.math.beta.BetaProto_pb2'
    # @@protoc_insertion_point(class_scope:BetasForSingleDayMsg.BetasTo)
    ))
  ,

  BetasFrom = _reflection.GeneratedProtocolMessageType('BetasFrom', (_message.Message,), dict(
    DESCRIPTOR = _BETASFORSINGLEDAYMSG_BETASFROM,
    __module__ = 'src.main.java.com.rb.nonbiz.math.beta.BetaProto_pb2'
    # @@protoc_insertion_point(class_scope:BetasForSingleDayMsg.BetasFrom)
    ))
  ,
  DESCRIPTOR = _BETASFORSINGLEDAYMSG,
  __module__ = 'src.main.java.com.rb.nonbiz.math.beta.BetaProto_pb2'
  # @@protoc_insertion_point(class_scope:BetasForSingleDayMsg)
  ))
_sym_db.RegisterMessage(BetasForSingleDayMsg)
_sym_db.RegisterMessage(BetasForSingleDayMsg.BetasTo)
_sym_db.RegisterMessage(BetasForSingleDayMsg.BetasFrom)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\027com.rb.nonbiz.math.beta'))
# @@protoc_insertion_point(module_scope)
