// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/com/rb/nonbiz/math/beta/BetaProto.proto

package com.rb.nonbiz.math.beta;

public final class BetaProto {
  private BetaProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BetasForSingleDayMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:BetasForSingleDayMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string human_description = 1;</code>
     */
    java.lang.String getHumanDescription();
    /**
     * <code>string human_description = 1;</code>
     */
    com.google.protobuf.ByteString
        getHumanDescriptionBytes();

    /**
     * <pre>
     * Ideally, we'll compute betas using this many days of history; but in some cases, we may be forced to use fewer;
     * that will show in BetasTo.actual_num_days_in_beta_calculation
     * </pre>
     *
     * <code>int32 max_num_days_in_beta_calculation = 2;</code>
     */
    int getMaxNumDaysInBetaCalculation();

    /**
     * <code>repeated .BetasForSingleDayMsg.BetasFrom betas_from = 3;</code>
     */
    java.util.List<com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasFrom> 
        getBetasFromList();
    /**
     * <code>repeated .BetasForSingleDayMsg.BetasFrom betas_from = 3;</code>
     */
    com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasFrom getBetasFrom(int index);
    /**
     * <code>repeated .BetasForSingleDayMsg.BetasFrom betas_from = 3;</code>
     */
    int getBetasFromCount();
    /**
     * <code>repeated .BetasForSingleDayMsg.BetasFrom betas_from = 3;</code>
     */
    java.util.List<? extends com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasFromOrBuilder> 
        getBetasFromOrBuilderList();
    /**
     * <code>repeated .BetasForSingleDayMsg.BetasFrom betas_from = 3;</code>
     */
    com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasFromOrBuilder getBetasFromOrBuilder(
        int index);
  }
  /**
   * <pre>
   * This format is verbose; we really could just do this with a 2d array (implemented as 1d because
   * protobuf doesn't support it), and store the row &amp; column keys separately.
   * This is what I had originally, but the problem is that it's hard to read the protobuf with automated tools.
   * The format below is maximally readable, even if it results in a bigger file on disk.
   * To save you the effort on how to protobuf-compile this:
   * cd ~/ssd/rb; protoc --java_out=./src/main/java ./src/main/java/com/rb/nonbiz/math/beta/BetaProto.proto
   * </pre>
   *
   * Protobuf type {@code BetasForSingleDayMsg}
   */
  public  static final class BetasForSingleDayMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:BetasForSingleDayMsg)
      BetasForSingleDayMsgOrBuilder {
    // Use BetasForSingleDayMsg.newBuilder() to construct.
    private BetasForSingleDayMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BetasForSingleDayMsg() {
      humanDescription_ = "";
      maxNumDaysInBetaCalculation_ = 0;
      betasFrom_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private BetasForSingleDayMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              humanDescription_ = s;
              break;
            }
            case 16: {

              maxNumDaysInBetaCalculation_ = input.readInt32();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                betasFrom_ = new java.util.ArrayList<com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasFrom>();
                mutable_bitField0_ |= 0x00000004;
              }
              betasFrom_.add(
                  input.readMessage(com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasFrom.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          betasFrom_ = java.util.Collections.unmodifiableList(betasFrom_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.rb.nonbiz.math.beta.BetaProto.internal_static_BetasForSingleDayMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.rb.nonbiz.math.beta.BetaProto.internal_static_BetasForSingleDayMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.class, com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.Builder.class);
    }

    public interface BetasToOrBuilder extends
        // @@protoc_insertion_point(interface_extends:BetasForSingleDayMsg.BetasTo)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>int64 to_instrument_id = 1;</code>
       */
      long getToInstrumentId();

      /**
       * <code>double beta = 2;</code>
       */
      double getBeta();

      /**
       * <pre>
       * Conceptually similar to QualityOfReturnsMsg in the eigendecomposition protobuf messages.
       * Ideally we'll be computing betas based on e.g. 250 days (or whatever the beta generation instructions say),
       * but in some cases we'll have to use a smaller amount of days, when insufficient days are available.
       * </pre>
       *
       * <code>int32 actual_num_days_in_beta_calculation = 3;</code>
       */
      int getActualNumDaysInBetaCalculation();

      /**
       * <code>double correlation = 4;</code>
       */
      double getCorrelation();
    }
    /**
     * Protobuf type {@code BetasForSingleDayMsg.BetasTo}
     */
    public  static final class BetasTo extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:BetasForSingleDayMsg.BetasTo)
        BetasToOrBuilder {
      // Use BetasTo.newBuilder() to construct.
      private BetasTo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private BetasTo() {
        toInstrumentId_ = 0L;
        beta_ = 0D;
        actualNumDaysInBetaCalculation_ = 0;
        correlation_ = 0D;
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
      }
      private BetasTo(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        int mutable_bitField0_ = 0;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 8: {

                toInstrumentId_ = input.readInt64();
                break;
              }
              case 17: {

                beta_ = input.readDouble();
                break;
              }
              case 24: {

                actualNumDaysInBetaCalculation_ = input.readInt32();
                break;
              }
              case 33: {

                correlation_ = input.readDouble();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.rb.nonbiz.math.beta.BetaProto.internal_static_BetasForSingleDayMsg_BetasTo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.rb.nonbiz.math.beta.BetaProto.internal_static_BetasForSingleDayMsg_BetasTo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasTo.class, com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasTo.Builder.class);
      }

      public static final int TO_INSTRUMENT_ID_FIELD_NUMBER = 1;
      private long toInstrumentId_;
      /**
       * <code>int64 to_instrument_id = 1;</code>
       */
      public long getToInstrumentId() {
        return toInstrumentId_;
      }

      public static final int BETA_FIELD_NUMBER = 2;
      private double beta_;
      /**
       * <code>double beta = 2;</code>
       */
      public double getBeta() {
        return beta_;
      }

      public static final int ACTUAL_NUM_DAYS_IN_BETA_CALCULATION_FIELD_NUMBER = 3;
      private int actualNumDaysInBetaCalculation_;
      /**
       * <pre>
       * Conceptually similar to QualityOfReturnsMsg in the eigendecomposition protobuf messages.
       * Ideally we'll be computing betas based on e.g. 250 days (or whatever the beta generation instructions say),
       * but in some cases we'll have to use a smaller amount of days, when insufficient days are available.
       * </pre>
       *
       * <code>int32 actual_num_days_in_beta_calculation = 3;</code>
       */
      public int getActualNumDaysInBetaCalculation() {
        return actualNumDaysInBetaCalculation_;
      }

      public static final int CORRELATION_FIELD_NUMBER = 4;
      private double correlation_;
      /**
       * <code>double correlation = 4;</code>
       */
      public double getCorrelation() {
        return correlation_;
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (toInstrumentId_ != 0L) {
          output.writeInt64(1, toInstrumentId_);
        }
        if (beta_ != 0D) {
          output.writeDouble(2, beta_);
        }
        if (actualNumDaysInBetaCalculation_ != 0) {
          output.writeInt32(3, actualNumDaysInBetaCalculation_);
        }
        if (correlation_ != 0D) {
          output.writeDouble(4, correlation_);
        }
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (toInstrumentId_ != 0L) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(1, toInstrumentId_);
        }
        if (beta_ != 0D) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(2, beta_);
        }
        if (actualNumDaysInBetaCalculation_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(3, actualNumDaysInBetaCalculation_);
        }
        if (correlation_ != 0D) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(4, correlation_);
        }
        memoizedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasTo)) {
          return super.equals(obj);
        }
        com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasTo other = (com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasTo) obj;

        boolean result = true;
        result = result && (getToInstrumentId()
            == other.getToInstrumentId());
        result = result && (
            java.lang.Double.doubleToLongBits(getBeta())
            == java.lang.Double.doubleToLongBits(
                other.getBeta()));
        result = result && (getActualNumDaysInBetaCalculation()
            == other.getActualNumDaysInBetaCalculation());
        result = result && (
            java.lang.Double.doubleToLongBits(getCorrelation())
            == java.lang.Double.doubleToLongBits(
                other.getCorrelation()));
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + TO_INSTRUMENT_ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getToInstrumentId());
        hash = (37 * hash) + BETA_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getBeta()));
        hash = (37 * hash) + ACTUAL_NUM_DAYS_IN_BETA_CALCULATION_FIELD_NUMBER;
        hash = (53 * hash) + getActualNumDaysInBetaCalculation();
        hash = (37 * hash) + CORRELATION_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getCorrelation()));
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasTo parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasTo parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasTo parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasTo parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasTo parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasTo parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasTo parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasTo parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasTo parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasTo parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasTo prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code BetasForSingleDayMsg.BetasTo}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:BetasForSingleDayMsg.BetasTo)
          com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasToOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.rb.nonbiz.math.beta.BetaProto.internal_static_BetasForSingleDayMsg_BetasTo_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.rb.nonbiz.math.beta.BetaProto.internal_static_BetasForSingleDayMsg_BetasTo_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasTo.class, com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasTo.Builder.class);
        }

        // Construct using com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasTo.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          toInstrumentId_ = 0L;

          beta_ = 0D;

          actualNumDaysInBetaCalculation_ = 0;

          correlation_ = 0D;

          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.rb.nonbiz.math.beta.BetaProto.internal_static_BetasForSingleDayMsg_BetasTo_descriptor;
        }

        public com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasTo getDefaultInstanceForType() {
          return com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasTo.getDefaultInstance();
        }

        public com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasTo build() {
          com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasTo result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasTo buildPartial() {
          com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasTo result = new com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasTo(this);
          result.toInstrumentId_ = toInstrumentId_;
          result.beta_ = beta_;
          result.actualNumDaysInBetaCalculation_ = actualNumDaysInBetaCalculation_;
          result.correlation_ = correlation_;
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasTo) {
            return mergeFrom((com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasTo)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasTo other) {
          if (other == com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasTo.getDefaultInstance()) return this;
          if (other.getToInstrumentId() != 0L) {
            setToInstrumentId(other.getToInstrumentId());
          }
          if (other.getBeta() != 0D) {
            setBeta(other.getBeta());
          }
          if (other.getActualNumDaysInBetaCalculation() != 0) {
            setActualNumDaysInBetaCalculation(other.getActualNumDaysInBetaCalculation());
          }
          if (other.getCorrelation() != 0D) {
            setCorrelation(other.getCorrelation());
          }
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasTo parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasTo) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private long toInstrumentId_ ;
        /**
         * <code>int64 to_instrument_id = 1;</code>
         */
        public long getToInstrumentId() {
          return toInstrumentId_;
        }
        /**
         * <code>int64 to_instrument_id = 1;</code>
         */
        public Builder setToInstrumentId(long value) {
          
          toInstrumentId_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int64 to_instrument_id = 1;</code>
         */
        public Builder clearToInstrumentId() {
          
          toInstrumentId_ = 0L;
          onChanged();
          return this;
        }

        private double beta_ ;
        /**
         * <code>double beta = 2;</code>
         */
        public double getBeta() {
          return beta_;
        }
        /**
         * <code>double beta = 2;</code>
         */
        public Builder setBeta(double value) {
          
          beta_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>double beta = 2;</code>
         */
        public Builder clearBeta() {
          
          beta_ = 0D;
          onChanged();
          return this;
        }

        private int actualNumDaysInBetaCalculation_ ;
        /**
         * <pre>
         * Conceptually similar to QualityOfReturnsMsg in the eigendecomposition protobuf messages.
         * Ideally we'll be computing betas based on e.g. 250 days (or whatever the beta generation instructions say),
         * but in some cases we'll have to use a smaller amount of days, when insufficient days are available.
         * </pre>
         *
         * <code>int32 actual_num_days_in_beta_calculation = 3;</code>
         */
        public int getActualNumDaysInBetaCalculation() {
          return actualNumDaysInBetaCalculation_;
        }
        /**
         * <pre>
         * Conceptually similar to QualityOfReturnsMsg in the eigendecomposition protobuf messages.
         * Ideally we'll be computing betas based on e.g. 250 days (or whatever the beta generation instructions say),
         * but in some cases we'll have to use a smaller amount of days, when insufficient days are available.
         * </pre>
         *
         * <code>int32 actual_num_days_in_beta_calculation = 3;</code>
         */
        public Builder setActualNumDaysInBetaCalculation(int value) {
          
          actualNumDaysInBetaCalculation_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         * Conceptually similar to QualityOfReturnsMsg in the eigendecomposition protobuf messages.
         * Ideally we'll be computing betas based on e.g. 250 days (or whatever the beta generation instructions say),
         * but in some cases we'll have to use a smaller amount of days, when insufficient days are available.
         * </pre>
         *
         * <code>int32 actual_num_days_in_beta_calculation = 3;</code>
         */
        public Builder clearActualNumDaysInBetaCalculation() {
          
          actualNumDaysInBetaCalculation_ = 0;
          onChanged();
          return this;
        }

        private double correlation_ ;
        /**
         * <code>double correlation = 4;</code>
         */
        public double getCorrelation() {
          return correlation_;
        }
        /**
         * <code>double correlation = 4;</code>
         */
        public Builder setCorrelation(double value) {
          
          correlation_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>double correlation = 4;</code>
         */
        public Builder clearCorrelation() {
          
          correlation_ = 0D;
          onChanged();
          return this;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return this;
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return this;
        }


        // @@protoc_insertion_point(builder_scope:BetasForSingleDayMsg.BetasTo)
      }

      // @@protoc_insertion_point(class_scope:BetasForSingleDayMsg.BetasTo)
      private static final com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasTo DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasTo();
      }

      public static com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasTo getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<BetasTo>
          PARSER = new com.google.protobuf.AbstractParser<BetasTo>() {
        public BetasTo parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return new BetasTo(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<BetasTo> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<BetasTo> getParserForType() {
        return PARSER;
      }

      public com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasTo getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public interface BetasFromOrBuilder extends
        // @@protoc_insertion_point(interface_extends:BetasForSingleDayMsg.BetasFrom)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>int64 from_instrument_id = 1;</code>
       */
      long getFromInstrumentId();

      /**
       * <code>repeated .BetasForSingleDayMsg.BetasTo betas_to = 2;</code>
       */
      java.util.List<com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasTo> 
          getBetasToList();
      /**
       * <code>repeated .BetasForSingleDayMsg.BetasTo betas_to = 2;</code>
       */
      com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasTo getBetasTo(int index);
      /**
       * <code>repeated .BetasForSingleDayMsg.BetasTo betas_to = 2;</code>
       */
      int getBetasToCount();
      /**
       * <code>repeated .BetasForSingleDayMsg.BetasTo betas_to = 2;</code>
       */
      java.util.List<? extends com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasToOrBuilder> 
          getBetasToOrBuilderList();
      /**
       * <code>repeated .BetasForSingleDayMsg.BetasTo betas_to = 2;</code>
       */
      com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasToOrBuilder getBetasToOrBuilder(
          int index);
    }
    /**
     * Protobuf type {@code BetasForSingleDayMsg.BetasFrom}
     */
    public  static final class BetasFrom extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:BetasForSingleDayMsg.BetasFrom)
        BetasFromOrBuilder {
      // Use BetasFrom.newBuilder() to construct.
      private BetasFrom(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private BetasFrom() {
        fromInstrumentId_ = 0L;
        betasTo_ = java.util.Collections.emptyList();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
      }
      private BetasFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        int mutable_bitField0_ = 0;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 8: {

                fromInstrumentId_ = input.readInt64();
                break;
              }
              case 18: {
                if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                  betasTo_ = new java.util.ArrayList<com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasTo>();
                  mutable_bitField0_ |= 0x00000002;
                }
                betasTo_.add(
                    input.readMessage(com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasTo.parser(), extensionRegistry));
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
            betasTo_ = java.util.Collections.unmodifiableList(betasTo_);
          }
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.rb.nonbiz.math.beta.BetaProto.internal_static_BetasForSingleDayMsg_BetasFrom_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.rb.nonbiz.math.beta.BetaProto.internal_static_BetasForSingleDayMsg_BetasFrom_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasFrom.class, com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasFrom.Builder.class);
      }

      private int bitField0_;
      public static final int FROM_INSTRUMENT_ID_FIELD_NUMBER = 1;
      private long fromInstrumentId_;
      /**
       * <code>int64 from_instrument_id = 1;</code>
       */
      public long getFromInstrumentId() {
        return fromInstrumentId_;
      }

      public static final int BETAS_TO_FIELD_NUMBER = 2;
      private java.util.List<com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasTo> betasTo_;
      /**
       * <code>repeated .BetasForSingleDayMsg.BetasTo betas_to = 2;</code>
       */
      public java.util.List<com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasTo> getBetasToList() {
        return betasTo_;
      }
      /**
       * <code>repeated .BetasForSingleDayMsg.BetasTo betas_to = 2;</code>
       */
      public java.util.List<? extends com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasToOrBuilder> 
          getBetasToOrBuilderList() {
        return betasTo_;
      }
      /**
       * <code>repeated .BetasForSingleDayMsg.BetasTo betas_to = 2;</code>
       */
      public int getBetasToCount() {
        return betasTo_.size();
      }
      /**
       * <code>repeated .BetasForSingleDayMsg.BetasTo betas_to = 2;</code>
       */
      public com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasTo getBetasTo(int index) {
        return betasTo_.get(index);
      }
      /**
       * <code>repeated .BetasForSingleDayMsg.BetasTo betas_to = 2;</code>
       */
      public com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasToOrBuilder getBetasToOrBuilder(
          int index) {
        return betasTo_.get(index);
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (fromInstrumentId_ != 0L) {
          output.writeInt64(1, fromInstrumentId_);
        }
        for (int i = 0; i < betasTo_.size(); i++) {
          output.writeMessage(2, betasTo_.get(i));
        }
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (fromInstrumentId_ != 0L) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(1, fromInstrumentId_);
        }
        for (int i = 0; i < betasTo_.size(); i++) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(2, betasTo_.get(i));
        }
        memoizedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasFrom)) {
          return super.equals(obj);
        }
        com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasFrom other = (com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasFrom) obj;

        boolean result = true;
        result = result && (getFromInstrumentId()
            == other.getFromInstrumentId());
        result = result && getBetasToList()
            .equals(other.getBetasToList());
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + FROM_INSTRUMENT_ID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getFromInstrumentId());
        if (getBetasToCount() > 0) {
          hash = (37 * hash) + BETAS_TO_FIELD_NUMBER;
          hash = (53 * hash) + getBetasToList().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasFrom parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasFrom parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasFrom parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasFrom parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasFrom parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasFrom parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasFrom parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasFrom parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasFrom parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasFrom parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasFrom prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code BetasForSingleDayMsg.BetasFrom}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:BetasForSingleDayMsg.BetasFrom)
          com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasFromOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.rb.nonbiz.math.beta.BetaProto.internal_static_BetasForSingleDayMsg_BetasFrom_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.rb.nonbiz.math.beta.BetaProto.internal_static_BetasForSingleDayMsg_BetasFrom_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasFrom.class, com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasFrom.Builder.class);
        }

        // Construct using com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasFrom.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
            getBetasToFieldBuilder();
          }
        }
        public Builder clear() {
          super.clear();
          fromInstrumentId_ = 0L;

          if (betasToBuilder_ == null) {
            betasTo_ = java.util.Collections.emptyList();
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            betasToBuilder_.clear();
          }
          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.rb.nonbiz.math.beta.BetaProto.internal_static_BetasForSingleDayMsg_BetasFrom_descriptor;
        }

        public com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasFrom getDefaultInstanceForType() {
          return com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasFrom.getDefaultInstance();
        }

        public com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasFrom build() {
          com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasFrom result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasFrom buildPartial() {
          com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasFrom result = new com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasFrom(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          result.fromInstrumentId_ = fromInstrumentId_;
          if (betasToBuilder_ == null) {
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
              betasTo_ = java.util.Collections.unmodifiableList(betasTo_);
              bitField0_ = (bitField0_ & ~0x00000002);
            }
            result.betasTo_ = betasTo_;
          } else {
            result.betasTo_ = betasToBuilder_.build();
          }
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasFrom) {
            return mergeFrom((com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasFrom)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasFrom other) {
          if (other == com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasFrom.getDefaultInstance()) return this;
          if (other.getFromInstrumentId() != 0L) {
            setFromInstrumentId(other.getFromInstrumentId());
          }
          if (betasToBuilder_ == null) {
            if (!other.betasTo_.isEmpty()) {
              if (betasTo_.isEmpty()) {
                betasTo_ = other.betasTo_;
                bitField0_ = (bitField0_ & ~0x00000002);
              } else {
                ensureBetasToIsMutable();
                betasTo_.addAll(other.betasTo_);
              }
              onChanged();
            }
          } else {
            if (!other.betasTo_.isEmpty()) {
              if (betasToBuilder_.isEmpty()) {
                betasToBuilder_.dispose();
                betasToBuilder_ = null;
                betasTo_ = other.betasTo_;
                bitField0_ = (bitField0_ & ~0x00000002);
                betasToBuilder_ = 
                  com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                     getBetasToFieldBuilder() : null;
              } else {
                betasToBuilder_.addAllMessages(other.betasTo_);
              }
            }
          }
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasFrom parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasFrom) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private long fromInstrumentId_ ;
        /**
         * <code>int64 from_instrument_id = 1;</code>
         */
        public long getFromInstrumentId() {
          return fromInstrumentId_;
        }
        /**
         * <code>int64 from_instrument_id = 1;</code>
         */
        public Builder setFromInstrumentId(long value) {
          
          fromInstrumentId_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int64 from_instrument_id = 1;</code>
         */
        public Builder clearFromInstrumentId() {
          
          fromInstrumentId_ = 0L;
          onChanged();
          return this;
        }

        private java.util.List<com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasTo> betasTo_ =
          java.util.Collections.emptyList();
        private void ensureBetasToIsMutable() {
          if (!((bitField0_ & 0x00000002) == 0x00000002)) {
            betasTo_ = new java.util.ArrayList<com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasTo>(betasTo_);
            bitField0_ |= 0x00000002;
           }
        }

        private com.google.protobuf.RepeatedFieldBuilderV3<
            com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasTo, com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasTo.Builder, com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasToOrBuilder> betasToBuilder_;

        /**
         * <code>repeated .BetasForSingleDayMsg.BetasTo betas_to = 2;</code>
         */
        public java.util.List<com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasTo> getBetasToList() {
          if (betasToBuilder_ == null) {
            return java.util.Collections.unmodifiableList(betasTo_);
          } else {
            return betasToBuilder_.getMessageList();
          }
        }
        /**
         * <code>repeated .BetasForSingleDayMsg.BetasTo betas_to = 2;</code>
         */
        public int getBetasToCount() {
          if (betasToBuilder_ == null) {
            return betasTo_.size();
          } else {
            return betasToBuilder_.getCount();
          }
        }
        /**
         * <code>repeated .BetasForSingleDayMsg.BetasTo betas_to = 2;</code>
         */
        public com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasTo getBetasTo(int index) {
          if (betasToBuilder_ == null) {
            return betasTo_.get(index);
          } else {
            return betasToBuilder_.getMessage(index);
          }
        }
        /**
         * <code>repeated .BetasForSingleDayMsg.BetasTo betas_to = 2;</code>
         */
        public Builder setBetasTo(
            int index, com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasTo value) {
          if (betasToBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            ensureBetasToIsMutable();
            betasTo_.set(index, value);
            onChanged();
          } else {
            betasToBuilder_.setMessage(index, value);
          }
          return this;
        }
        /**
         * <code>repeated .BetasForSingleDayMsg.BetasTo betas_to = 2;</code>
         */
        public Builder setBetasTo(
            int index, com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasTo.Builder builderForValue) {
          if (betasToBuilder_ == null) {
            ensureBetasToIsMutable();
            betasTo_.set(index, builderForValue.build());
            onChanged();
          } else {
            betasToBuilder_.setMessage(index, builderForValue.build());
          }
          return this;
        }
        /**
         * <code>repeated .BetasForSingleDayMsg.BetasTo betas_to = 2;</code>
         */
        public Builder addBetasTo(com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasTo value) {
          if (betasToBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            ensureBetasToIsMutable();
            betasTo_.add(value);
            onChanged();
          } else {
            betasToBuilder_.addMessage(value);
          }
          return this;
        }
        /**
         * <code>repeated .BetasForSingleDayMsg.BetasTo betas_to = 2;</code>
         */
        public Builder addBetasTo(
            int index, com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasTo value) {
          if (betasToBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            ensureBetasToIsMutable();
            betasTo_.add(index, value);
            onChanged();
          } else {
            betasToBuilder_.addMessage(index, value);
          }
          return this;
        }
        /**
         * <code>repeated .BetasForSingleDayMsg.BetasTo betas_to = 2;</code>
         */
        public Builder addBetasTo(
            com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasTo.Builder builderForValue) {
          if (betasToBuilder_ == null) {
            ensureBetasToIsMutable();
            betasTo_.add(builderForValue.build());
            onChanged();
          } else {
            betasToBuilder_.addMessage(builderForValue.build());
          }
          return this;
        }
        /**
         * <code>repeated .BetasForSingleDayMsg.BetasTo betas_to = 2;</code>
         */
        public Builder addBetasTo(
            int index, com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasTo.Builder builderForValue) {
          if (betasToBuilder_ == null) {
            ensureBetasToIsMutable();
            betasTo_.add(index, builderForValue.build());
            onChanged();
          } else {
            betasToBuilder_.addMessage(index, builderForValue.build());
          }
          return this;
        }
        /**
         * <code>repeated .BetasForSingleDayMsg.BetasTo betas_to = 2;</code>
         */
        public Builder addAllBetasTo(
            java.lang.Iterable<? extends com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasTo> values) {
          if (betasToBuilder_ == null) {
            ensureBetasToIsMutable();
            com.google.protobuf.AbstractMessageLite.Builder.addAll(
                values, betasTo_);
            onChanged();
          } else {
            betasToBuilder_.addAllMessages(values);
          }
          return this;
        }
        /**
         * <code>repeated .BetasForSingleDayMsg.BetasTo betas_to = 2;</code>
         */
        public Builder clearBetasTo() {
          if (betasToBuilder_ == null) {
            betasTo_ = java.util.Collections.emptyList();
            bitField0_ = (bitField0_ & ~0x00000002);
            onChanged();
          } else {
            betasToBuilder_.clear();
          }
          return this;
        }
        /**
         * <code>repeated .BetasForSingleDayMsg.BetasTo betas_to = 2;</code>
         */
        public Builder removeBetasTo(int index) {
          if (betasToBuilder_ == null) {
            ensureBetasToIsMutable();
            betasTo_.remove(index);
            onChanged();
          } else {
            betasToBuilder_.remove(index);
          }
          return this;
        }
        /**
         * <code>repeated .BetasForSingleDayMsg.BetasTo betas_to = 2;</code>
         */
        public com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasTo.Builder getBetasToBuilder(
            int index) {
          return getBetasToFieldBuilder().getBuilder(index);
        }
        /**
         * <code>repeated .BetasForSingleDayMsg.BetasTo betas_to = 2;</code>
         */
        public com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasToOrBuilder getBetasToOrBuilder(
            int index) {
          if (betasToBuilder_ == null) {
            return betasTo_.get(index);  } else {
            return betasToBuilder_.getMessageOrBuilder(index);
          }
        }
        /**
         * <code>repeated .BetasForSingleDayMsg.BetasTo betas_to = 2;</code>
         */
        public java.util.List<? extends com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasToOrBuilder> 
             getBetasToOrBuilderList() {
          if (betasToBuilder_ != null) {
            return betasToBuilder_.getMessageOrBuilderList();
          } else {
            return java.util.Collections.unmodifiableList(betasTo_);
          }
        }
        /**
         * <code>repeated .BetasForSingleDayMsg.BetasTo betas_to = 2;</code>
         */
        public com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasTo.Builder addBetasToBuilder() {
          return getBetasToFieldBuilder().addBuilder(
              com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasTo.getDefaultInstance());
        }
        /**
         * <code>repeated .BetasForSingleDayMsg.BetasTo betas_to = 2;</code>
         */
        public com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasTo.Builder addBetasToBuilder(
            int index) {
          return getBetasToFieldBuilder().addBuilder(
              index, com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasTo.getDefaultInstance());
        }
        /**
         * <code>repeated .BetasForSingleDayMsg.BetasTo betas_to = 2;</code>
         */
        public java.util.List<com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasTo.Builder> 
             getBetasToBuilderList() {
          return getBetasToFieldBuilder().getBuilderList();
        }
        private com.google.protobuf.RepeatedFieldBuilderV3<
            com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasTo, com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasTo.Builder, com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasToOrBuilder> 
            getBetasToFieldBuilder() {
          if (betasToBuilder_ == null) {
            betasToBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasTo, com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasTo.Builder, com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasToOrBuilder>(
                    betasTo_,
                    ((bitField0_ & 0x00000002) == 0x00000002),
                    getParentForChildren(),
                    isClean());
            betasTo_ = null;
          }
          return betasToBuilder_;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return this;
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return this;
        }


        // @@protoc_insertion_point(builder_scope:BetasForSingleDayMsg.BetasFrom)
      }

      // @@protoc_insertion_point(class_scope:BetasForSingleDayMsg.BetasFrom)
      private static final com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasFrom DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasFrom();
      }

      public static com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasFrom getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<BetasFrom>
          PARSER = new com.google.protobuf.AbstractParser<BetasFrom>() {
        public BetasFrom parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
            return new BetasFrom(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<BetasFrom> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<BetasFrom> getParserForType() {
        return PARSER;
      }

      public com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasFrom getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int HUMAN_DESCRIPTION_FIELD_NUMBER = 1;
    private volatile java.lang.Object humanDescription_;
    /**
     * <code>string human_description = 1;</code>
     */
    public java.lang.String getHumanDescription() {
      java.lang.Object ref = humanDescription_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        humanDescription_ = s;
        return s;
      }
    }
    /**
     * <code>string human_description = 1;</code>
     */
    public com.google.protobuf.ByteString
        getHumanDescriptionBytes() {
      java.lang.Object ref = humanDescription_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        humanDescription_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MAX_NUM_DAYS_IN_BETA_CALCULATION_FIELD_NUMBER = 2;
    private int maxNumDaysInBetaCalculation_;
    /**
     * <pre>
     * Ideally, we'll compute betas using this many days of history; but in some cases, we may be forced to use fewer;
     * that will show in BetasTo.actual_num_days_in_beta_calculation
     * </pre>
     *
     * <code>int32 max_num_days_in_beta_calculation = 2;</code>
     */
    public int getMaxNumDaysInBetaCalculation() {
      return maxNumDaysInBetaCalculation_;
    }

    public static final int BETAS_FROM_FIELD_NUMBER = 3;
    private java.util.List<com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasFrom> betasFrom_;
    /**
     * <code>repeated .BetasForSingleDayMsg.BetasFrom betas_from = 3;</code>
     */
    public java.util.List<com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasFrom> getBetasFromList() {
      return betasFrom_;
    }
    /**
     * <code>repeated .BetasForSingleDayMsg.BetasFrom betas_from = 3;</code>
     */
    public java.util.List<? extends com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasFromOrBuilder> 
        getBetasFromOrBuilderList() {
      return betasFrom_;
    }
    /**
     * <code>repeated .BetasForSingleDayMsg.BetasFrom betas_from = 3;</code>
     */
    public int getBetasFromCount() {
      return betasFrom_.size();
    }
    /**
     * <code>repeated .BetasForSingleDayMsg.BetasFrom betas_from = 3;</code>
     */
    public com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasFrom getBetasFrom(int index) {
      return betasFrom_.get(index);
    }
    /**
     * <code>repeated .BetasForSingleDayMsg.BetasFrom betas_from = 3;</code>
     */
    public com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasFromOrBuilder getBetasFromOrBuilder(
        int index) {
      return betasFrom_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getHumanDescriptionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, humanDescription_);
      }
      if (maxNumDaysInBetaCalculation_ != 0) {
        output.writeInt32(2, maxNumDaysInBetaCalculation_);
      }
      for (int i = 0; i < betasFrom_.size(); i++) {
        output.writeMessage(3, betasFrom_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getHumanDescriptionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, humanDescription_);
      }
      if (maxNumDaysInBetaCalculation_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, maxNumDaysInBetaCalculation_);
      }
      for (int i = 0; i < betasFrom_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, betasFrom_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg)) {
        return super.equals(obj);
      }
      com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg other = (com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg) obj;

      boolean result = true;
      result = result && getHumanDescription()
          .equals(other.getHumanDescription());
      result = result && (getMaxNumDaysInBetaCalculation()
          == other.getMaxNumDaysInBetaCalculation());
      result = result && getBetasFromList()
          .equals(other.getBetasFromList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + HUMAN_DESCRIPTION_FIELD_NUMBER;
      hash = (53 * hash) + getHumanDescription().hashCode();
      hash = (37 * hash) + MAX_NUM_DAYS_IN_BETA_CALCULATION_FIELD_NUMBER;
      hash = (53 * hash) + getMaxNumDaysInBetaCalculation();
      if (getBetasFromCount() > 0) {
        hash = (37 * hash) + BETAS_FROM_FIELD_NUMBER;
        hash = (53 * hash) + getBetasFromList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * This format is verbose; we really could just do this with a 2d array (implemented as 1d because
     * protobuf doesn't support it), and store the row &amp; column keys separately.
     * This is what I had originally, but the problem is that it's hard to read the protobuf with automated tools.
     * The format below is maximally readable, even if it results in a bigger file on disk.
     * To save you the effort on how to protobuf-compile this:
     * cd ~/ssd/rb; protoc --java_out=./src/main/java ./src/main/java/com/rb/nonbiz/math/beta/BetaProto.proto
     * </pre>
     *
     * Protobuf type {@code BetasForSingleDayMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:BetasForSingleDayMsg)
        com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.rb.nonbiz.math.beta.BetaProto.internal_static_BetasForSingleDayMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.rb.nonbiz.math.beta.BetaProto.internal_static_BetasForSingleDayMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.class, com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.Builder.class);
      }

      // Construct using com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getBetasFromFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        humanDescription_ = "";

        maxNumDaysInBetaCalculation_ = 0;

        if (betasFromBuilder_ == null) {
          betasFrom_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          betasFromBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.rb.nonbiz.math.beta.BetaProto.internal_static_BetasForSingleDayMsg_descriptor;
      }

      public com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg getDefaultInstanceForType() {
        return com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.getDefaultInstance();
      }

      public com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg build() {
        com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg buildPartial() {
        com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg result = new com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.humanDescription_ = humanDescription_;
        result.maxNumDaysInBetaCalculation_ = maxNumDaysInBetaCalculation_;
        if (betasFromBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            betasFrom_ = java.util.Collections.unmodifiableList(betasFrom_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.betasFrom_ = betasFrom_;
        } else {
          result.betasFrom_ = betasFromBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg) {
          return mergeFrom((com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg other) {
        if (other == com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.getDefaultInstance()) return this;
        if (!other.getHumanDescription().isEmpty()) {
          humanDescription_ = other.humanDescription_;
          onChanged();
        }
        if (other.getMaxNumDaysInBetaCalculation() != 0) {
          setMaxNumDaysInBetaCalculation(other.getMaxNumDaysInBetaCalculation());
        }
        if (betasFromBuilder_ == null) {
          if (!other.betasFrom_.isEmpty()) {
            if (betasFrom_.isEmpty()) {
              betasFrom_ = other.betasFrom_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureBetasFromIsMutable();
              betasFrom_.addAll(other.betasFrom_);
            }
            onChanged();
          }
        } else {
          if (!other.betasFrom_.isEmpty()) {
            if (betasFromBuilder_.isEmpty()) {
              betasFromBuilder_.dispose();
              betasFromBuilder_ = null;
              betasFrom_ = other.betasFrom_;
              bitField0_ = (bitField0_ & ~0x00000004);
              betasFromBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getBetasFromFieldBuilder() : null;
            } else {
              betasFromBuilder_.addAllMessages(other.betasFrom_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object humanDescription_ = "";
      /**
       * <code>string human_description = 1;</code>
       */
      public java.lang.String getHumanDescription() {
        java.lang.Object ref = humanDescription_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          humanDescription_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string human_description = 1;</code>
       */
      public com.google.protobuf.ByteString
          getHumanDescriptionBytes() {
        java.lang.Object ref = humanDescription_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          humanDescription_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string human_description = 1;</code>
       */
      public Builder setHumanDescription(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        humanDescription_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string human_description = 1;</code>
       */
      public Builder clearHumanDescription() {
        
        humanDescription_ = getDefaultInstance().getHumanDescription();
        onChanged();
        return this;
      }
      /**
       * <code>string human_description = 1;</code>
       */
      public Builder setHumanDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        humanDescription_ = value;
        onChanged();
        return this;
      }

      private int maxNumDaysInBetaCalculation_ ;
      /**
       * <pre>
       * Ideally, we'll compute betas using this many days of history; but in some cases, we may be forced to use fewer;
       * that will show in BetasTo.actual_num_days_in_beta_calculation
       * </pre>
       *
       * <code>int32 max_num_days_in_beta_calculation = 2;</code>
       */
      public int getMaxNumDaysInBetaCalculation() {
        return maxNumDaysInBetaCalculation_;
      }
      /**
       * <pre>
       * Ideally, we'll compute betas using this many days of history; but in some cases, we may be forced to use fewer;
       * that will show in BetasTo.actual_num_days_in_beta_calculation
       * </pre>
       *
       * <code>int32 max_num_days_in_beta_calculation = 2;</code>
       */
      public Builder setMaxNumDaysInBetaCalculation(int value) {
        
        maxNumDaysInBetaCalculation_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Ideally, we'll compute betas using this many days of history; but in some cases, we may be forced to use fewer;
       * that will show in BetasTo.actual_num_days_in_beta_calculation
       * </pre>
       *
       * <code>int32 max_num_days_in_beta_calculation = 2;</code>
       */
      public Builder clearMaxNumDaysInBetaCalculation() {
        
        maxNumDaysInBetaCalculation_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasFrom> betasFrom_ =
        java.util.Collections.emptyList();
      private void ensureBetasFromIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          betasFrom_ = new java.util.ArrayList<com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasFrom>(betasFrom_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasFrom, com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasFrom.Builder, com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasFromOrBuilder> betasFromBuilder_;

      /**
       * <code>repeated .BetasForSingleDayMsg.BetasFrom betas_from = 3;</code>
       */
      public java.util.List<com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasFrom> getBetasFromList() {
        if (betasFromBuilder_ == null) {
          return java.util.Collections.unmodifiableList(betasFrom_);
        } else {
          return betasFromBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .BetasForSingleDayMsg.BetasFrom betas_from = 3;</code>
       */
      public int getBetasFromCount() {
        if (betasFromBuilder_ == null) {
          return betasFrom_.size();
        } else {
          return betasFromBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .BetasForSingleDayMsg.BetasFrom betas_from = 3;</code>
       */
      public com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasFrom getBetasFrom(int index) {
        if (betasFromBuilder_ == null) {
          return betasFrom_.get(index);
        } else {
          return betasFromBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .BetasForSingleDayMsg.BetasFrom betas_from = 3;</code>
       */
      public Builder setBetasFrom(
          int index, com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasFrom value) {
        if (betasFromBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBetasFromIsMutable();
          betasFrom_.set(index, value);
          onChanged();
        } else {
          betasFromBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .BetasForSingleDayMsg.BetasFrom betas_from = 3;</code>
       */
      public Builder setBetasFrom(
          int index, com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasFrom.Builder builderForValue) {
        if (betasFromBuilder_ == null) {
          ensureBetasFromIsMutable();
          betasFrom_.set(index, builderForValue.build());
          onChanged();
        } else {
          betasFromBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .BetasForSingleDayMsg.BetasFrom betas_from = 3;</code>
       */
      public Builder addBetasFrom(com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasFrom value) {
        if (betasFromBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBetasFromIsMutable();
          betasFrom_.add(value);
          onChanged();
        } else {
          betasFromBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .BetasForSingleDayMsg.BetasFrom betas_from = 3;</code>
       */
      public Builder addBetasFrom(
          int index, com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasFrom value) {
        if (betasFromBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBetasFromIsMutable();
          betasFrom_.add(index, value);
          onChanged();
        } else {
          betasFromBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .BetasForSingleDayMsg.BetasFrom betas_from = 3;</code>
       */
      public Builder addBetasFrom(
          com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasFrom.Builder builderForValue) {
        if (betasFromBuilder_ == null) {
          ensureBetasFromIsMutable();
          betasFrom_.add(builderForValue.build());
          onChanged();
        } else {
          betasFromBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .BetasForSingleDayMsg.BetasFrom betas_from = 3;</code>
       */
      public Builder addBetasFrom(
          int index, com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasFrom.Builder builderForValue) {
        if (betasFromBuilder_ == null) {
          ensureBetasFromIsMutable();
          betasFrom_.add(index, builderForValue.build());
          onChanged();
        } else {
          betasFromBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .BetasForSingleDayMsg.BetasFrom betas_from = 3;</code>
       */
      public Builder addAllBetasFrom(
          java.lang.Iterable<? extends com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasFrom> values) {
        if (betasFromBuilder_ == null) {
          ensureBetasFromIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, betasFrom_);
          onChanged();
        } else {
          betasFromBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .BetasForSingleDayMsg.BetasFrom betas_from = 3;</code>
       */
      public Builder clearBetasFrom() {
        if (betasFromBuilder_ == null) {
          betasFrom_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          betasFromBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .BetasForSingleDayMsg.BetasFrom betas_from = 3;</code>
       */
      public Builder removeBetasFrom(int index) {
        if (betasFromBuilder_ == null) {
          ensureBetasFromIsMutable();
          betasFrom_.remove(index);
          onChanged();
        } else {
          betasFromBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .BetasForSingleDayMsg.BetasFrom betas_from = 3;</code>
       */
      public com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasFrom.Builder getBetasFromBuilder(
          int index) {
        return getBetasFromFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .BetasForSingleDayMsg.BetasFrom betas_from = 3;</code>
       */
      public com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasFromOrBuilder getBetasFromOrBuilder(
          int index) {
        if (betasFromBuilder_ == null) {
          return betasFrom_.get(index);  } else {
          return betasFromBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .BetasForSingleDayMsg.BetasFrom betas_from = 3;</code>
       */
      public java.util.List<? extends com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasFromOrBuilder> 
           getBetasFromOrBuilderList() {
        if (betasFromBuilder_ != null) {
          return betasFromBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(betasFrom_);
        }
      }
      /**
       * <code>repeated .BetasForSingleDayMsg.BetasFrom betas_from = 3;</code>
       */
      public com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasFrom.Builder addBetasFromBuilder() {
        return getBetasFromFieldBuilder().addBuilder(
            com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasFrom.getDefaultInstance());
      }
      /**
       * <code>repeated .BetasForSingleDayMsg.BetasFrom betas_from = 3;</code>
       */
      public com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasFrom.Builder addBetasFromBuilder(
          int index) {
        return getBetasFromFieldBuilder().addBuilder(
            index, com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasFrom.getDefaultInstance());
      }
      /**
       * <code>repeated .BetasForSingleDayMsg.BetasFrom betas_from = 3;</code>
       */
      public java.util.List<com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasFrom.Builder> 
           getBetasFromBuilderList() {
        return getBetasFromFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasFrom, com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasFrom.Builder, com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasFromOrBuilder> 
          getBetasFromFieldBuilder() {
        if (betasFromBuilder_ == null) {
          betasFromBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasFrom, com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasFrom.Builder, com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg.BetasFromOrBuilder>(
                  betasFrom_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          betasFrom_ = null;
        }
        return betasFromBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:BetasForSingleDayMsg)
    }

    // @@protoc_insertion_point(class_scope:BetasForSingleDayMsg)
    private static final com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg();
    }

    public static com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BetasForSingleDayMsg>
        PARSER = new com.google.protobuf.AbstractParser<BetasForSingleDayMsg>() {
      public BetasForSingleDayMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new BetasForSingleDayMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BetasForSingleDayMsg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BetasForSingleDayMsg> getParserForType() {
      return PARSER;
    }

    public com.rb.nonbiz.math.beta.BetaProto.BetasForSingleDayMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BetasForSingleDayMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BetasForSingleDayMsg_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BetasForSingleDayMsg_BetasTo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BetasForSingleDayMsg_BetasTo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BetasForSingleDayMsg_BetasFrom_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BetasForSingleDayMsg_BetasFrom_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n5src/main/java/com/rb/nonbiz/math/beta/" +
      "BetaProto.proto\"\337\002\n\024BetasForSingleDayMsg" +
      "\022\031\n\021human_description\030\001 \001(\t\022(\n max_num_d" +
      "ays_in_beta_calculation\030\002 \001(\005\0223\n\nbetas_f" +
      "rom\030\003 \003(\0132\037.BetasForSingleDayMsg.BetasFr" +
      "om\032s\n\007BetasTo\022\030\n\020to_instrument_id\030\001 \001(\003\022" +
      "\014\n\004beta\030\002 \001(\001\022+\n#actual_num_days_in_beta" +
      "_calculation\030\003 \001(\005\022\023\n\013correlation\030\004 \001(\001\032" +
      "X\n\tBetasFrom\022\032\n\022from_instrument_id\030\001 \001(\003" +
      "\022/\n\010betas_to\030\002 \003(\0132\035.BetasForSingleDayMs",
      "g.BetasToB\031\n\027com.rb.nonbiz.math.betab\006pr" +
      "oto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_BetasForSingleDayMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_BetasForSingleDayMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BetasForSingleDayMsg_descriptor,
        new java.lang.String[] { "HumanDescription", "MaxNumDaysInBetaCalculation", "BetasFrom", });
    internal_static_BetasForSingleDayMsg_BetasTo_descriptor =
      internal_static_BetasForSingleDayMsg_descriptor.getNestedTypes().get(0);
    internal_static_BetasForSingleDayMsg_BetasTo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BetasForSingleDayMsg_BetasTo_descriptor,
        new java.lang.String[] { "ToInstrumentId", "Beta", "ActualNumDaysInBetaCalculation", "Correlation", });
    internal_static_BetasForSingleDayMsg_BetasFrom_descriptor =
      internal_static_BetasForSingleDayMsg_descriptor.getNestedTypes().get(1);
    internal_static_BetasForSingleDayMsg_BetasFrom_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BetasForSingleDayMsg_BetasFrom_descriptor,
        new java.lang.String[] { "FromInstrumentId", "BetasTo", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
